wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/assets/arch_linux.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/assets/arch_linux.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/.config/hypr/assets/arch_linux.png
    fit_mode = cover
}

splash = true
